language: node_js
sudo: false

env:
  - SENECA_VER=@1.x.x
  - SENECA_VER=@2.x.x
  - SENECA_VER=@3.x.x

node_js:
  - "7"

before_script:
  - npm uninstall seneca
  - npm install seneca$SENECA_VER

after_script:
  npm run coveralls
