sudo: false
language: node_js

env:
  - SENECA_VER=seneca@2.x.x
  - SENECA_VER=seneca@3.x.x
  - SENECA_VER=seneca@plugin
  - SENECA_VER=senecajs/seneca

node_js:
  - "8"
  - "6"
  - "4"

before_script:
  - npm uninstall seneca
  - npm install $SENECA_VER

after_script:
  - npm run coveralls
